package main

const (
	CONFIG_FILE_PATH = "./config.json"

	DEFAULT_DELIMITTER = "^"

	DEFAULT_OUTPUT_DIRECTORY = "./out"
	DEFAULT_LAYERS_DIRECTORY = "./layers"

	DEFAULT_ARTWORK_WIDTH  = 512
	DEFAULT_ARTWORK_HEIGHT = 512

	DEFAULT_ELEMENT_WEIGHT = 1

	DEFAULT_LAYER_OPACITY = 1

	DEFAULT_GIF_DELAY  = 50
	DEFAULT_GIF_REPEAT = 0
)

var INVALID_DELIMITTERS = []string{".", ",", ""}
