package main

const CONFIG_FILE_PATH = "./config.json"

const DEFAULT_DELIMITTER = "^"
const DEFAULT_OUTPUT_DIRECTORY = "./out"
const DEFAULT_LAYERS_DIRECTORY = "./layers"

const DEFAULT_ARTWORK_WIDTH = 512
const DEFAULT_ARTWORK_HEIGHT = 512
const DEFAULT_ELEMENT_WEIGHT = 1
const DEFAULT_LAYER_OPACITY = 1

var INVALID_DELIMITTERS = []string{".", ",", ""}

const DEFAULT_GIF_DELAY = 50
const DEFAULT_GIF_REPEAT = 0
